config/routes.rb
Rails.application.routes.draw do
  get 'post/index'
  get 'profil/index',to:"profil#index", as: 'profil'
  get 'my_campaign/index'
  get 'message/index', to:"message#index", as: 'message'
  get 'participe_campagne/index/:id', to: 'participe_campagne#index', as: 'participe_campagne'
  get 'post_campaign/:id', to:"post_campaign#index", as:'postCampaign'
  get 'participe/index/:id', to:"participe#index", as: 'participe'
  get 'c_disponible/index'
  root 'login#index'
  get 'auth/:provider/callback', to:"sessions#create", as: 'fbVerification'
  delete 'sign_out', to:'sessions#destroy', as:'sign_out'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
	has_many :messages
	has_many :users, through: :messages
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/campaign.rb
class Campaign < ApplicationRecord
	has_many :posts
	has_many :users, through: :posts
	has_many :campaignImages
end

app/models/campaign_image.rb
class CampaignImage < ApplicationRecord
  belongs_to :campaign
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :admin
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :campaign
end

app/models/user.rb
class User < ApplicationRecord
	has_many :posts
	has_many :campaigns, through: :posts
	has_many :messages
	has_many :admins, through: :messages

	def self.sign_in_from_omniauth(auth)
		find_by(provider: auth['provider'], uid: auth['uid']) || create_user_from_omniauth(auth)
	end

	def self.create_user_from_omniauth(auth)
		create(
			provider: auth['provider'],
			uid: auth['uid'],
			name: auth['info']['name']
		)
	end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  before_action :set_auth

  def index
  	
  end

  def set_auth
    @auth = session[:omniauth] if session[:omniauth]
  end

end

app/controllers/message_controller.rb
class MessageController < ApplicationController
  def index
  end
end

app/controllers/post_campaign_controller.rb
class PostCampaignController < ApplicationController
	def index
		@campaign_selected = Campaign.find(params[:id])
		@campaign_galery_images = CampaignImage.joins(:campaign).where(campaign_id: params[:id])
	end
end

app/controllers/post_controller.rb
class PostController < ApplicationController
  def index
  end
end

app/controllers/profil_controller.rb
class ProfilController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/c_disponible_helper.rb
module CDisponibleHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/my_campaign_helper.rb
module MyCampaignHelper
end

app/helpers/participe_helper.rb
module ParticipeHelper
end

app/helpers/post_campaign_helper.rb
module PostCampaignHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/profil_helper.rb
module ProfilHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/post_campaign/index.html.erb
		<%= @campaign_selected.id %>
		<div class="page-content--bge5">
			<div class="container">
				<div class="login-wrap">
					<div class="login-content">
						<div class="login-logo">
							<div class="title"><span><a href=""><img src="/image/icone/pictogramme/retour.png" alt="return-bottom", class= 'return'></span></a>
								<p class="c_title">Participe campagne</p>
							</div>
						</div>
					</div>
					<!-- Swiper -->
					<div class="swiper-container">
						<div class="swiper-wrapper">
							<div class="swiper-slide">
								<div class="swiper-campagne">
									<div class="swiper-title">
										<h4><%= @campaign_selected.name %></h4>
									</div>
									<% @campaign_galery_images.each do |cpi|%>
										<div class="swiper-head">
											<img src="/image/fond/<%= cpi.name %>" alt="building" class="ImgCamp"/>
											<h2 class="country"><%= @campaign_selected.location %></h2>
											<%= image_tag '/image/icone/drapeau/canada.png', alt: 'canada', class: "img-flag" %>
										</div>
									<% end%>
									<div class="swiper-description">
										<p>Date de lancement de la campagne: <%= @campaign_selected.date%>
										</br>Budget: 500€
										<br>Déjà gagné: 275€
										<br>Reste à gagné: 225€
									</p>
								</div>
								<div class="swiper-brief">
									<h3 class="title">Brief</h3>
									<p class="definition">
										<%= @campaign_selected.description %>
									</p>
								</div>
								<hr class="separate">
								<div class="swiper-tag">
									<h3 class="tag-identity">Tag et compte à identifier</h3><span class="fas fa-chevron-right"></span>
									<p><%= @campaign_selected.hashtag %></p>
								</div>
								<hr class="separate">
								<div class="swiper-type">
									<h3 class="type">Type de campagne</h3><span class="fas fa-chevron-right"></span>
								</div>
								<hr class="separate">
								<div class="swiper-criterion">
									<h3 class="criterion">Critère et taille apprécié</h3><span class="fas fa-chevron-right"></span>
								</div>
								<hr class="separate">
								<div class="bottom">
									<a href="<%= participe_path(id: @campaign_selected.id) %>" class="bottom_participe bouton"><span></span>Participer</a>
									<a href="" class="bottom-liste bouton"><span></span>Liste</a>
								</div>
							</div>
						</div>
						<div class="swiper-slide">
							<img src="/image/fond/ville.jpg" alt="ville" class="ImgCamp"/>
						</div>
					</div>
				</div>
				<div class="footer-division">
					<a href="">
						<%= image_tag "/image/footer/Loupe.png", alt: "loop", class: 'picto' %>
					</a>
					<a href="">
						<%= image_tag "/image/footer/Coeur.png", alt: "Coeur", class: 'picto' %>
					</a>
					<a href="">
						<%= image_tag "/image/footer/Euro.png", alt: "Euro", class: 'picto' %>
					</a>
					<a href="<%= message_path %>">
						<%= image_tag "/image/footer/Message.png", alt: "Message", class: 'picto' %>
					</a>
					<a href="<%= profil_path %>">
						<%= image_tag "/image/footer/Profile.png", alt: "Profile", class: 'picto' %>
					</a>
				</div>  