config/routes.rb
Rails.application.routes.draw do
  get 'post/index'
  get 'profil/index',to:"profil#index", as: 'profil'
  get 'my_campaign/index'
  get 'message/index', to:"message#index", as: 'message'
  get 'participe_campagne/index/:id', to: 'participe_campagne#index', as: 'participe_campagne'
  get 'post_campaign/:id', to:"post_campaign#index", as:'postCampaign'
  get 'participe/index/:id', to:"participe#index", as: 'participe'
  get 'c_disponible/index'
  root 'login#index'
  get 'auth/:provider/callback', to:"sessions#create", as: 'fbVerification'
  delete 'sign_out', to:'sessions#destroy', as:'sign_out'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
	has_many :messages
	has_many :users, through: :messages
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/campaign.rb
class Campaign < ApplicationRecord
	has_many :posts
	has_many :users, through: :posts
	has_many :campaignImages
end

app/models/campaign_image.rb
class CampaignImage < ApplicationRecord
  belongs_to :campaign
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :admin
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :campaign
end

app/models/user.rb
class User < ApplicationRecord
	has_many :posts
	has_many :campaigns, through: :posts
	has_many :messages
	has_many :admins, through: :messages

	def self.sign_in_from_omniauth(auth)
		find_by(provider: auth['provider'], uid: auth['uid']) || create_user_from_omniauth(auth)
	end

	def self.create_user_from_omniauth(auth)
		create(
			provider: auth['provider'],
			uid: auth['uid'],
			name: auth['info']['name']
		)
	end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  before_action :set_auth

  def index
  	
  end

  def set_auth
    @auth = session[:omniauth] if session[:omniauth]
  end

end

app/controllers/message_controller.rb
class MessageController < ApplicationController
  def index
  end
end

app/controllers/participe_controller.rb
class ParticipeController < ApplicationController
  def index
  	@campaign_selected = Campaign.find(params[:id])
	@campaign_galery_images = CampaignImage.joins(:campaign).where(campaign_id: params[:id])
  end
end

app/controllers/post_controller.rb
class PostController < ApplicationController
  def index
  end
end

app/controllers/profil_controller.rb
class ProfilController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/c_disponible_helper.rb
module CDisponibleHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/my_campaign_helper.rb
module MyCampaignHelper
end

app/helpers/participe_helper.rb
module ParticipeHelper
end

app/helpers/post_campaign_helper.rb
module PostCampaignHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/profil_helper.rb
module ProfilHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/participe/index.html.erb
<link rel="stylesheet" href="css/style-participe.css">

<body class="animsition">
	<!-- <div class="page-wrapper"> -->
		<div class="page-content--bge5">
			<div class="container">
				<div class="login-wrap">
					<div class="login-content">
						<div class="login-logo">
						    <div class="title"><a href=""><span><%= image_tag '/image/icone/pictogramme/retour.png', class: 'return' %></span></a>
                            <p class="c_title">Participer</p>
							</div>
						</div>
					</div>
	<!-- <div class="details"> -->
			<main class="main-detail">
				<div class="detail-title">
					<div class="title-campaign">
						<p clas="campaign"><%= @campaign_selected.name %><span><%= image_tag '/image/icone/drapeau/canada.png', alt: 'canada', class: "flag" %></span></p>
					</div>
					<div class="campaign-detail">
						<h4 class="post-description">Post type (modifiable)<span class="fas fa-pencil-alt"></span>
						</h4>
						<div class="description-article">
							<p class="description">
								<%= @campaign_selected.description %>
							</p>
						</div>
						<!-- <div class="ligne de séparament"> -->
						<div class="drawn-separate">
							<hr>
						</div>

						<div>
							<h4 class="post-description">Photos Proposées</h4>
						</div>
						<!-- <div class="image"> -->
						<div class="Diaporama">
							<% @campaign_galery_images.each do |cgi|%>
								<%= image_tag '/image/fond/'+cgi.name, alt: 'montagne', class: 'diaporama-position' %>
							<% end %>
						</div>

						<div class="botton-post">
							<a href="<%= participe_campagne_path(id:@campaign_selected.id)%>" class=""></a>
						</div>
						<div class="button-camera">
							<button type="submit" class="activation-camera" name="camera-activation" >
								<span class="fa fa-camera"></span>
							</button>
						</div>
					</div>
				</div>	
			</main>
            <div class="footer-division">
				<a href="">
					<%= image_tag "/image/footer/Loupe.png", alt: "loop", class: 'picto' %>
				</a>
				<a href="">
					<%= image_tag "/image/footer/Coeur.png", alt: "Coeur", class: 'picto' %>
				</a>
				<a href="">
					<%= image_tag "/image/footer/Euro.png", alt: "Euro", class: 'picto' %>
				</a>
				<a href="<%= message_path %>">
					<%= image_tag "/image/footer/Message.png", alt: "Message", class: 'picto' %>
				</a>
				<a href="<%= profil_path %>">
					<%= image_tag "/image/footer/Profile.png", alt: "Profile", class: 'picto' %>
				</a>
			</div>
			    </div>
	        </div>
        </div>
</body>